-- ============================================================================
-- SUPABASE IMAGE URL UPDATE SCRIPT
-- Generated: 2026-02-04T13:52:15.469Z
-- ============================================================================
-- Run this script in Supabase SQL Editor
-- Make sure to backup your data before running!
-- ============================================================================

BEGIN;

-- ============================================================================
-- CATEGORIES (12 rows)
-- ============================================================================

UPDATE categories SET image_url = 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/18NBcSJ4uEq7tnlpgk-BWlpgXwxrdfFnQ.jpg' WHERE id = 18;
UPDATE categories SET image_url = 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1m8SQtMA_FIKoxjuFyObgRuWb4FhSoKTB.jpg' WHERE id = 19;
UPDATE categories SET image_url = 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1quXP6qyf7RCsqVMx-whinwyOq3RbpWUP.jpg' WHERE id = 20;
UPDATE categories SET image_url = 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1pakES7s6DfgqpqAlkbfv11GwNNos611I.jpg' WHERE id = 21;
UPDATE categories SET image_url = 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1eNKqMn_EXJC3G8ErtPRkKByt47INwcI-.jpg' WHERE id = 22;
UPDATE categories SET image_url = 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1QGB9jGWTmngr8CTIDqcPcn1vj7S1bjnm.jpg' WHERE id = 23;
UPDATE categories SET image_url = 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1W9nME0wveK8kRNh4jcqznvXwEyfIeUiH.jpg' WHERE id = 24;
UPDATE categories SET image_url = 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/14AysIFw4epWeJaZFdQ1JTU5bVblJNwwS.jpg' WHERE id = 25;
UPDATE categories SET image_url = 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/150G3yddjTTbmWXhBUorPOxzuyj4luU3v.jpg' WHERE id = 26;
UPDATE categories SET image_url = 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1BRBBL8OvNWOluODbbkeRCQv2BWQA9yDJ.jpg' WHERE id = 27;
UPDATE categories SET image_url = 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1GsXZ2SpDEWdt6PpFGmJ0Cr6gA7achyEF.jpg' WHERE id = 28;
UPDATE categories SET image_url = 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1qyzTP9eM9QHmEP-o3mS5Xlr0ccLPRTsV.jpg' WHERE id = 29;

-- ============================================================================
-- SUB-CATEGORIES (26 rows)
-- ============================================================================

UPDATE "sub-categories" SET image_url = 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1pakES7s6DfgqpqAlkbfv11GwNNos611I.jpg' WHERE id = 21;
UPDATE "sub-categories" SET image_url = 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1GsXZ2SpDEWdt6PpFGmJ0Cr6gA7achyEF.jpg' WHERE id = 22;
UPDATE "sub-categories" SET image_url = 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1P6LiSh0udPs0ISsBzSiEqWZO6NRMIBqd.jpg' WHERE id = 20;
UPDATE "sub-categories" SET image_url = 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1quXP6qyf7RCsqVMx-whinwyOq3RbpWUP.jpg' WHERE id = 14;
UPDATE "sub-categories" SET image_url = 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1hmS5a2oDzZiSYcl3YulGVpeMmf9MmF7x.jpg' WHERE id = 15;
UPDATE "sub-categories" SET image_url = 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1zygyrZxY-I6GdI4XUgqN9W2azICcDYi1.jpg' WHERE id = 16;
UPDATE "sub-categories" SET image_url = 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/169mWY-zo0kYPzBm97cyk53oItEeQxv2E.jpg' WHERE id = 19;
UPDATE "sub-categories" SET image_url = 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1_94UOzMOz9FVPXIGxYpHlLJiARME01v8.jpg' WHERE id = 17;
UPDATE "sub-categories" SET image_url = 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1rbkHZsQgRc7DVnLdV5SJeVGMW_wb100Z.jpg' WHERE id = 10;
UPDATE "sub-categories" SET image_url = 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1t2QHMl7IFUoFC7qWqh4DrRU4TF48aBNC.jpg' WHERE id = 11;
UPDATE "sub-categories" SET image_url = 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1JsOIlV7GerGLG30VSCKoC4xdZt8iRpG9.jpg' WHERE id = 18;
UPDATE "sub-categories" SET image_url = 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1Wx3J8JWYVxlKaKxTXM17Fp56n__Vfib6.jpg' WHERE id = 8;
UPDATE "sub-categories" SET image_url = 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ZVZQ1FrTRcAOuxw4oUg3d12p1tvsKiWa.jpg' WHERE id = 12;
UPDATE "sub-categories" SET image_url = 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1lDIicBhzy4ydBFrj9vvJOumrB3mQeoXU.jpg' WHERE id = 23;
UPDATE "sub-categories" SET image_url = 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1yyxWo3HdipcswUC1famc5H5ig_wHpDCd.jpg' WHERE id = 33;
UPDATE "sub-categories" SET image_url = 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1qyzTP9eM9QHmEP-o3mS5Xlr0ccLPRTsV.jpg' WHERE id = 29;
UPDATE "sub-categories" SET image_url = 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/16_68kSDHZh73HjOlDjn5iUTR0qNytFcv.jpg' WHERE id = 13;
UPDATE "sub-categories" SET image_url = 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1_2cPJcwpcYcFO0G6h-ovOBHgc5tO60Id.jpg' WHERE id = 30;
UPDATE "sub-categories" SET image_url = 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NzxrhlxUc9A9KEBV0bBstzitXaroBDkr.jpg' WHERE id = 31;
UPDATE "sub-categories" SET image_url = 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1BRBBL8OvNWOluODbbkeRCQv2BWQA9yDJ.jpg' WHERE id = 32;
UPDATE "sub-categories" SET image_url = 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XpTO_iCwrLrL1tsX4dlJ9VE2MP7t8vfz.jpg' WHERE id = 24;
UPDATE "sub-categories" SET image_url = 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1nRQDXt9p1JmIKBYpfjsIy9iWZ7i60dsi.jpg' WHERE id = 9;
UPDATE "sub-categories" SET image_url = 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1SbuyzR_E2E8A4MNHBm35HrUM6BCu50iE.jpg' WHERE id = 25;
UPDATE "sub-categories" SET image_url = 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/107IkYBwxb9brCTq9nCAJZ2qc9mZmduHA.jpg' WHERE id = 26;
UPDATE "sub-categories" SET image_url = 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1fKLQmKGKyUnN4n90TNLiCPPW6cHTs84C.jpg' WHERE id = 28;
UPDATE "sub-categories" SET image_url = 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1Rntg3M4cq3ovbWbChts5o3uF8LZaReoN.jpg' WHERE id = 27;

-- ============================================================================
-- PRODUCTS (146 rows)
-- ============================================================================

UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1SbuyzR_E2E8A4MNHBm35HrUM6BCu50iE.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/11lcTIgRZZJ9MIMfgkLQsqOBz3F-zhu-_.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 157;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1JsOIlV7GerGLG30VSCKoC4xdZt8iRpG9.jpg'] WHERE id = 189;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1m8SQtMA_FIKoxjuFyObgRuWb4FhSoKTB.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1959iCSrDXtz6nsjvMZsvOzbwe1O5t-26.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 197;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1Rntg3M4cq3ovbWbChts5o3uF8LZaReoN.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 167;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/107IkYBwxb9brCTq9nCAJZ2qc9mZmduHA.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/15udDD1nGvV2PvCJ3iVE_FmcEgvaUCWTx.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 160;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XpTO_iCwrLrL1tsX4dlJ9VE2MP7t8vfz.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1cWFHljy98DElg6N5tI-czdin0i89eqq_.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 106;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1eNKqMn_EXJC3G8ErtPRkKByt47INwcI-.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1s658yNgsC4CVFiuO59WsKCojGkyb_Jk1.jpg'] WHERE id = 63;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1SbuyzR_E2E8A4MNHBm35HrUM6BCu50iE.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1-tR3XqLK0fqb1wuFbmQbqTseR1G54Djo.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 137;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1rbkHZsQgRc7DVnLdV5SJeVGMW_wb100Z.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1YlW5Lha5LyrgHQYm_W40-Jw4Q2K5sCjT.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 37;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1pakES7s6DfgqpqAlkbfv11GwNNos611I.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1Pmf4wargz_aL5RkZFf0xkou0MFZQInLn.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XIf2qZEpguDSpGObYJehdb49oXMzqCy6.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg'] WHERE id = 91;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1p6mZ-TJB8ZeXDxsnAesW2WwsalWIbpaq.jpg'] WHERE id = 180;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1qyzTP9eM9QHmEP-o3mS5Xlr0ccLPRTsV.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1rjQVe95Jy8nDh41NZEu3XuT2j60VhkS5.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 176;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1BRBBL8OvNWOluODbbkeRCQv2BWQA9yDJ.jpg'] WHERE id = 195;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1yyxWo3HdipcswUC1famc5H5ig_wHpDCd.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1-uqE2kqQvsAVCRbo8kyTnbNjDUdipHZ6.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 198;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1quXP6qyf7RCsqVMx-whinwyOq3RbpWUP.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1BW-rL67c92lBtZDyNfOQ3SdjrO_s5TQB.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XIf2qZEpguDSpGObYJehdb49oXMzqCy6.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg'] WHERE id = 57;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1fKLQmKGKyUnN4n90TNLiCPPW6cHTs84C.jpg'] WHERE id = 200;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1Wx3J8JWYVxlKaKxTXM17Fp56n__Vfib6.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1PgoSvktg8I1XySbDmsFqNjHBAQ3DeWdE.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 68;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1pakES7s6DfgqpqAlkbfv11GwNNos611I.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1QykMRMFI1Jn8V60EvO5kYZRv27e-dG1u.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XIf2qZEpguDSpGObYJehdb49oXMzqCy6.jpg'] WHERE id = 83;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1t2QHMl7IFUoFC7qWqh4DrRU4TF48aBNC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 49;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ZVZQ1FrTRcAOuxw4oUg3d12p1tvsKiWa.jpg'] WHERE id = 53;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1GsXZ2SpDEWdt6PpFGmJ0Cr6gA7achyEF.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1iS8YRs4n8YDe8LyuqWKxinqRTdY4ML02.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XIf2qZEpguDSpGObYJehdb49oXMzqCy6.jpg'] WHERE id = 86;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/13KHSRuAQwuQOwfpqar7zUiZBcbUHhel1.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1m5HQCE0-9MMY3fei_WkvlL_-4knU2tip.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XIf2qZEpguDSpGObYJehdb49oXMzqCy6.jpg'] WHERE id = 191;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1P6LiSh0udPs0ISsBzSiEqWZO6NRMIBqd.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1khbPDEsMjN8fXMwNSiMxNLPRQX1aHgqd.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 84;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1JsOIlV7GerGLG30VSCKoC4xdZt8iRpG9.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/12QS3Z5wrSptcZ9j9Y3WOFvc8ZvMS_6fG.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XIf2qZEpguDSpGObYJehdb49oXMzqCy6.jpg'] WHERE id = 90;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1yv4nTQE93UsaKfFUMdbAFkXWIwVN3E8Y.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1bIukYg8Z_ifvv6vuCeXyoRIJOFLXpp_q.jpg'] WHERE id = 92;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/169mWY-zo0kYPzBm97cyk53oItEeQxv2E.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XIf2qZEpguDSpGObYJehdb49oXMzqCy6.jpg'] WHERE id = 72;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1Wx3J8JWYVxlKaKxTXM17Fp56n__Vfib6.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/104HfNoPIIRxtsOcZexhw3ObNArcZmqKL.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 94;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1nRQDXt9p1JmIKBYpfjsIy9iWZ7i60dsi.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/13Y7YQqmnoaWw5WoCeRyStBdBaEPHJzT6.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 124;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/169mWY-zo0kYPzBm97cyk53oItEeQxv2E.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XIf2qZEpguDSpGObYJehdb49oXMzqCy6.jpg'] WHERE id = 74;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1Wx3J8JWYVxlKaKxTXM17Fp56n__Vfib6.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1TUye-m1AISfapKud4WLXSGQorGs-BoHt.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 21;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ZVZQ1FrTRcAOuxw4oUg3d12p1tvsKiWa.jpg'] WHERE id = 54;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1quXP6qyf7RCsqVMx-whinwyOq3RbpWUP.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/15gHvIS-md-9vX5PorbaS0flJUOc_lZoA.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XIf2qZEpguDSpGObYJehdb49oXMzqCy6.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg'] WHERE id = 59;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1BzxatrTTtxpfpggY_aUBPXKvMSDmG40_.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1CQUkRGFGzzJFpEie_hdpoAgpeFLj7G35.jpg'] WHERE id = 88;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1eNKqMn_EXJC3G8ErtPRkKByt47INwcI-.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1MpdL6eg9i4TR0Hjoa5IDerq5A4sYCIkK.jpg'] WHERE id = 64;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1fKLQmKGKyUnN4n90TNLiCPPW6cHTs84C.jpg'] WHERE id = 201;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1nRQDXt9p1JmIKBYpfjsIy9iWZ7i60dsi.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ecsbVVINla28w3pn1I4-_7vBIPk02KHW.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 125;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1SbuyzR_E2E8A4MNHBm35HrUM6BCu50iE.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1LSr-o1mrJ_qJAGg2k_ovBugeMpbassi6.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 138;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1qyzTP9eM9QHmEP-o3mS5Xlr0ccLPRTsV.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1UlNezfm4e2b3Tf1RroDhZsuwy1Lt2LXb.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 177;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1p6mZ-TJB8ZeXDxsnAesW2WwsalWIbpaq.jpg'] WHERE id = 182;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1BRBBL8OvNWOluODbbkeRCQv2BWQA9yDJ.jpg'] WHERE id = 196;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1yyxWo3HdipcswUC1famc5H5ig_wHpDCd.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1F_Hm28ajKeLhqZLiesD4CwHWDNI_HPS8.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 199;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1Rntg3M4cq3ovbWbChts5o3uF8LZaReoN.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NNVpJ9w5QRJDHB0pCNEfOtSX1fHq59N7.jpg'] WHERE id = 168;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XpTO_iCwrLrL1tsX4dlJ9VE2MP7t8vfz.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1t6YkmPHgecyuzPGjz7rdku_JVSn3VLY6.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 107;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/107IkYBwxb9brCTq9nCAJZ2qc9mZmduHA.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1WWks-S85dTds6JZZBS3qAW5_3j9boLbb.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 161;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1rbkHZsQgRc7DVnLdV5SJeVGMW_wb100Z.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1fuPhxVaX2ldVZAJFAo7AgHCpNTLZYFVt.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 39;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1t2QHMl7IFUoFC7qWqh4DrRU4TF48aBNC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1GkH-UCWtE78gRhZV_xZnDtCkxWXY9_LO.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 50;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1HMX7Ale8Pmsm6GG2Ms8Y8CJSrJVGaIhx.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1yKXk0-try_-_9vjiFpK0GdryEMOQ11_A.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 85;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/13KHSRuAQwuQOwfpqar7zUiZBcbUHhel1.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/19xiTJE87Lram0Bb9Sc_KB5bQ_wdxhgBV.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XIf2qZEpguDSpGObYJehdb49oXMzqCy6.jpg'] WHERE id = 192;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1eNKqMn_EXJC3G8ErtPRkKByt47INwcI-.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1o7L7vXhxbxrAqwc4ub2vT1uWH8DRdBP6.jpg'] WHERE id = 66;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1SbuyzR_E2E8A4MNHBm35HrUM6BCu50iE.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XEi-Wfvn8YT-SyEsUBgGFApLuPvs6DPL.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 139;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XpTO_iCwrLrL1tsX4dlJ9VE2MP7t8vfz.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ylP-aEK_5ZZ-J0OQwdRgjnQBKUE162pw.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 108;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1Wx3J8JWYVxlKaKxTXM17Fp56n__Vfib6.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1bBkUwP91WvkwWL7utZdhRm0QclC66ulO.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 25;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/107IkYBwxb9brCTq9nCAJZ2qc9mZmduHA.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 162;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1t2QHMl7IFUoFC7qWqh4DrRU4TF48aBNC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ffHW9nTLyotI5QPEJTB8hLWAPDDv_8gL.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 52;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1fKLQmKGKyUnN4n90TNLiCPPW6cHTs84C.jpg'] WHERE id = 203;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1p6mZ-TJB8ZeXDxsnAesW2WwsalWIbpaq.jpg'] WHERE id = 183;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1nRQDXt9p1JmIKBYpfjsIy9iWZ7i60dsi.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1LCA8OG0AhItouF2TnXpZzdqbo_MibwiG.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 127;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1eNKqMn_EXJC3G8ErtPRkKByt47INwcI-.jpg'] WHERE id = 81;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1JsOIlV7GerGLG30VSCKoC4xdZt8iRpG9.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1Fhf0yvkG6GxaGdSXfDRz-uiZLKfwhzoS.jpg'] WHERE id = 190;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/13KHSRuAQwuQOwfpqar7zUiZBcbUHhel1.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1EvLWZZu5iTk2WNMoNHi4Zm9zDpvmMOBT.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XIf2qZEpguDSpGObYJehdb49oXMzqCy6.jpg'] WHERE id = 193;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ZVZQ1FrTRcAOuxw4oUg3d12p1tvsKiWa.jpg'] WHERE id = 55;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1quXP6qyf7RCsqVMx-whinwyOq3RbpWUP.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1Fhf0yvkG6GxaGdSXfDRz-uiZLKfwhzoS.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XIf2qZEpguDSpGObYJehdb49oXMzqCy6.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg'] WHERE id = 60;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/169mWY-zo0kYPzBm97cyk53oItEeQxv2E.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XIf2qZEpguDSpGObYJehdb49oXMzqCy6.jpg'] WHERE id = 75;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1rbkHZsQgRc7DVnLdV5SJeVGMW_wb100Z.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1O6aWZTZYAuqoSMSZCoY2MVUAstQM9OWe.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 41;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1Rntg3M4cq3ovbWbChts5o3uF8LZaReoN.jpg'] WHERE id = 169;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1eNKqMn_EXJC3G8ErtPRkKByt47INwcI-.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1hJOU1bzSVSVSqThzst3kazrvxoAkjXcG.jpg'] WHERE id = 194;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/107IkYBwxb9brCTq9nCAJZ2qc9mZmduHA.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 163;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XpTO_iCwrLrL1tsX4dlJ9VE2MP7t8vfz.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1bEzsR1FV_-TC1sd1TkABgTfHSAv1vy1q.jpg'] WHERE id = 109;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1fKLQmKGKyUnN4n90TNLiCPPW6cHTs84C.jpg'] WHERE id = 206;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1Rntg3M4cq3ovbWbChts5o3uF8LZaReoN.jpg'] WHERE id = 170;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/169mWY-zo0kYPzBm97cyk53oItEeQxv2E.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XIf2qZEpguDSpGObYJehdb49oXMzqCy6.jpg'] WHERE id = 77;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1eNKqMn_EXJC3G8ErtPRkKByt47INwcI-.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1Zoc8mFMGK5lpOaauBQiQ_gzFHWNwRu22.jpg'] WHERE id = 67;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1t2QHMl7IFUoFC7qWqh4DrRU4TF48aBNC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1KzCSiNt4c9IbD6bUSIxcRw3f8GxQkswW.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 187;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1az1ZFYj9y5yvxKGkGWWiWt1UrGbhkGmd.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1VzfWzO3mvQZPSWyZpfvuB77685uKJasn.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 56;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1Wx3J8JWYVxlKaKxTXM17Fp56n__Vfib6.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1_mABx53ZHDdCIBc96nhEnk4fJH-b1Ca7.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 26;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1p6mZ-TJB8ZeXDxsnAesW2WwsalWIbpaq.jpg'] WHERE id = 184;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1SbuyzR_E2E8A4MNHBm35HrUM6BCu50iE.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/13brAd6oNYneE72I53oiTdKaaEjjWjxcM.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 140;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1nRQDXt9p1JmIKBYpfjsIy9iWZ7i60dsi.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/19641zM48CBR3Obtwzl1INDFjksFz2fDU.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 128;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1m8SQtMA_FIKoxjuFyObgRuWb4FhSoKTB.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ucJUHt5S1SyeLQzTpMaT4hB43arrO2Bi.jpg'] WHERE id = 178;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1p6mZ-TJB8ZeXDxsnAesW2WwsalWIbpaq.jpg'] WHERE id = 186;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1m8SQtMA_FIKoxjuFyObgRuWb4FhSoKTB.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1jIHE69iTBBmU67tSwvPD0lzBi-X7PLZX.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 179;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1Rntg3M4cq3ovbWbChts5o3uF8LZaReoN.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/138jjhC2Aw1prlbXx5FriAUVkxGGsmluY.jpg'] WHERE id = 171;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1fKLQmKGKyUnN4n90TNLiCPPW6cHTs84C.jpg'] WHERE id = 207;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/169mWY-zo0kYPzBm97cyk53oItEeQxv2E.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1gZ7kPcOUedhpsUefbS9qbr2fG_j84Ri3.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XIf2qZEpguDSpGObYJehdb49oXMzqCy6.jpg'] WHERE id = 80;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XpTO_iCwrLrL1tsX4dlJ9VE2MP7t8vfz.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1hxh5Y9dAYfBunb32sE746LOZUqMyWdEf.jpg'] WHERE id = 110;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1t2QHMl7IFUoFC7qWqh4DrRU4TF48aBNC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1djCxZkBx5yrFL_oHIp9-E3WNocTRZa3n.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 188;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/107IkYBwxb9brCTq9nCAJZ2qc9mZmduHA.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 164;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1nRQDXt9p1JmIKBYpfjsIy9iWZ7i60dsi.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1_sDAW1qoGXvZu4Kcya5SkrP2p4gChFPl.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 44;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1SbuyzR_E2E8A4MNHBm35HrUM6BCu50iE.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NoS5GfUWjqSYakv-9Z-gH070E5TfDHWx.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 142;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1Wx3J8JWYVxlKaKxTXM17Fp56n__Vfib6.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1kdkpVhLpWxRwJSQyXnulrw1FNAmDGLLD.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 27;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1fKLQmKGKyUnN4n90TNLiCPPW6cHTs84C.jpg'] WHERE id = 208;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1nRQDXt9p1JmIKBYpfjsIy9iWZ7i60dsi.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vvWDFTsn_Zdk8QzUuDi1oykAGGXqqggY.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 45;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1Wx3J8JWYVxlKaKxTXM17Fp56n__Vfib6.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1IVmuevMpRoCIfqQpWzyg-AF7mncpCFDH.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 29;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1Rntg3M4cq3ovbWbChts5o3uF8LZaReoN.jpg'] WHERE id = 172;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1Rntg3M4cq3ovbWbChts5o3uF8LZaReoN.jpg'] WHERE id = 173;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1Wx3J8JWYVxlKaKxTXM17Fp56n__Vfib6.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1qb20hq2-mVyjzo0vhRbM480lD5dcVrqg.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 30;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1nRQDXt9p1JmIKBYpfjsIy9iWZ7i60dsi.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1DvxyW0WKFHGiI7HOOmU5v46B6Vssl1K-.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 46;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1SbuyzR_E2E8A4MNHBm35HrUM6BCu50iE.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XWCL5MG0z3vYxBU1aiRnO599qqBROCoO.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 145;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1fKLQmKGKyUnN4n90TNLiCPPW6cHTs84C.jpg'] WHERE id = 209;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/107IkYBwxb9brCTq9nCAJZ2qc9mZmduHA.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 165;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XpTO_iCwrLrL1tsX4dlJ9VE2MP7t8vfz.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1nNXyBO6nyecvX-ZQjPGHkcHlbY4bzYuw.jpg'] WHERE id = 112;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1SbuyzR_E2E8A4MNHBm35HrUM6BCu50iE.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1xU7tQN9SGe8OEXD8ld3MnbS-0QfEpKiY.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 144;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XpTO_iCwrLrL1tsX4dlJ9VE2MP7t8vfz.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1-88GhGq2rd4ML_sfIVq78caJdVCM7pll.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 113;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1Wx3J8JWYVxlKaKxTXM17Fp56n__Vfib6.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1B9odWo01UbfzwIJisgo_4c2EqgNNS6mO.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 89;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1Wx3J8JWYVxlKaKxTXM17Fp56n__Vfib6.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/18Ct1m7O4VQ0J7UG4FTNqySmHwhsUYR5S.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 96;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/107IkYBwxb9brCTq9nCAJZ2qc9mZmduHA.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 166;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XpTO_iCwrLrL1tsX4dlJ9VE2MP7t8vfz.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1Zx3KiTYyCOcA_ylo9IZIfKcRT5F1F70T.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 114;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1SbuyzR_E2E8A4MNHBm35HrUM6BCu50iE.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1z7TuK8YOuAKrDMkhrI_9DbAti6-TFJhY.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 148;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1Rntg3M4cq3ovbWbChts5o3uF8LZaReoN.jpg'] WHERE id = 174;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1nRQDXt9p1JmIKBYpfjsIy9iWZ7i60dsi.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1cWKmcZ63ktAA3Tc2GTSs1cgNgu0J-QRw.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 47;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XpTO_iCwrLrL1tsX4dlJ9VE2MP7t8vfz.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/19e3r_A7BBMtRwspkwUnRFq0j3mFYpwU6.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 115;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1Wx3J8JWYVxlKaKxTXM17Fp56n__Vfib6.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/18Ct1m7O4VQ0J7UG4FTNqySmHwhsUYR5S.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 98;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1SbuyzR_E2E8A4MNHBm35HrUM6BCu50iE.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/12LennogwGTEJvizhfD0xhileC82IvQ-n.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 150;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1nRQDXt9p1JmIKBYpfjsIy9iWZ7i60dsi.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1CBsDU-O7o-PmUQpxrDqxxMvvL7VGPRA5.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 130;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1Rntg3M4cq3ovbWbChts5o3uF8LZaReoN.jpg'] WHERE id = 175;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1SbuyzR_E2E8A4MNHBm35HrUM6BCu50iE.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NhhWmx9HX8hpHYK6jz3VdtklSEwn_-3e.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 151;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1nRQDXt9p1JmIKBYpfjsIy9iWZ7i60dsi.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1RT_yjwO4u7KYDex4rdz8upFCzfhWiWRg.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 48;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1Wx3J8JWYVxlKaKxTXM17Fp56n__Vfib6.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1c8Qo2CuH0OPpB-oS_3ELhJG6nWkF9k6d.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 99;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XpTO_iCwrLrL1tsX4dlJ9VE2MP7t8vfz.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/131PwrMez0gK26jOAk34XJQVTl5xbE4N9.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 116;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XpTO_iCwrLrL1tsX4dlJ9VE2MP7t8vfz.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1sYKMcdyqemi0Cf_p9ZKKXPjZ4q-FR1yz.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 117;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1nRQDXt9p1JmIKBYpfjsIy9iWZ7i60dsi.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1sI6i9W5728PDxNmOr6SmtK0-mHSSKbjm.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 131;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1Ip-w2wJfk7pKwwBGIbItoOQEAkSWhCcx.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1hvjCoAYiIUFY4QfBXA6bLC_d8HSzp9SO.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 152;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1Wx3J8JWYVxlKaKxTXM17Fp56n__Vfib6.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 101;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1Ip-w2wJfk7pKwwBGIbItoOQEAkSWhCcx.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1jjenwUt7nS3Bkha4-LdgkIT-YOrUCdDw.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 153;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1Wx3J8JWYVxlKaKxTXM17Fp56n__Vfib6.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 103;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XpTO_iCwrLrL1tsX4dlJ9VE2MP7t8vfz.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1fxD4L1LI995UnOUesMEr3c6yP2yyesQb.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 118;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1gtWkaa0oMSjtaI-C-3xi71gQ4cfSPeCR.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1Kri2WvO2A_NMMa0qf0xd1Z_v2plJge61.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 69;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1Wx3J8JWYVxlKaKxTXM17Fp56n__Vfib6.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1BZ2lWIWiAakxSoASgh7LU9bPkmUqJ2hi.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 104;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1Ip-w2wJfk7pKwwBGIbItoOQEAkSWhCcx.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/17Gqj4FviHYKeDFo2Oa8p2vlhYLrqf1pl.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 154;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1nRQDXt9p1JmIKBYpfjsIy9iWZ7i60dsi.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1dEp9MJKdmjOo4aKJwASwE_F3vamaEkdt.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 132;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XpTO_iCwrLrL1tsX4dlJ9VE2MP7t8vfz.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 119;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/157_x2dwCb7SKvYVanuqcFZNnsrqiuYRv.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1RG_UKvfkuzVPobTe-kBVjvPtt8Be-EEJ.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 71;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1Ip-w2wJfk7pKwwBGIbItoOQEAkSWhCcx.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1sosVIXZeePSOHutximGI6c71XUr_i3p_.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 155;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XpTO_iCwrLrL1tsX4dlJ9VE2MP7t8vfz.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 120;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1Wx3J8JWYVxlKaKxTXM17Fp56n__Vfib6.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/15452yJYflrut13U6CUrSfKi9h3bSNwBD.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 105;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XpTO_iCwrLrL1tsX4dlJ9VE2MP7t8vfz.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 121;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1Wx3J8JWYVxlKaKxTXM17Fp56n__Vfib6.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1pAoJR8_EdAO3rIodAtCUF-3tm9-Shamx.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 31;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1nRQDXt9p1JmIKBYpfjsIy9iWZ7i60dsi.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/10T5tWadCQra-Q0mq19t6yn-dp08kX_RQ.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 133;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1SbuyzR_E2E8A4MNHBm35HrUM6BCu50iE.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/17Gqj4FviHYKeDFo2Oa8p2vlhYLrqf1pl.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 156;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XpTO_iCwrLrL1tsX4dlJ9VE2MP7t8vfz.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 122;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1nRQDXt9p1JmIKBYpfjsIy9iWZ7i60dsi.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1bLc1g0cMTSGN3lcvO6oT1LUX5IHnXY8l.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 134;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1SbuyzR_E2E8A4MNHBm35HrUM6BCu50iE.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1oIxhk4uVAQI7HXIoWYSwhTXl1Bg9YNMc.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 158;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XpTO_iCwrLrL1tsX4dlJ9VE2MP7t8vfz.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1DnN2d_Ocr7L--Jhj1ogfbPpFrS6dCWDa.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 123;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1nRQDXt9p1JmIKBYpfjsIy9iWZ7i60dsi.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1LTmALE4ONXqnBtjxTBaT_kNUYrzN1rQY.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 135;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1nRQDXt9p1JmIKBYpfjsIy9iWZ7i60dsi.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1rTy0GfoHl-H9LANU0E4I4wbuBQNYQx8A.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 136;
UPDATE product SET image_url = ARRAY['https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1SbuyzR_E2E8A4MNHBm35HrUM6BCu50iE.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1FG2azVG7NtXy3-lwgYGKws1R_pJe31ue.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1XKo3Xv_Z6tE-0C7MA1ueSWe_og8ixbdC.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1NyMq5WvSx4URm7vxlTM572-6p6KHO-al.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1ACuY9F9apnL450_FoiXL4F_LBii5cvOh.jpg', 'https://ik.imagekit.io/fq27eon0z/threadcart/migrated/1vVmHCCFJs0Dlc_zrXjpAkcDRLOpBunAm.jpg'] WHERE id = 159;

-- ============================================================================
-- VERIFY CHANGES (uncomment to check)
-- ============================================================================
-- SELECT id, name, image_url FROM categories LIMIT 5;
-- SELECT id, name, image_url FROM "sub-categories" LIMIT 5;
-- SELECT id, name, image_url FROM product LIMIT 5;

COMMIT;

-- ============================================================================
-- ROLLBACK (run this if something goes wrong)
-- ============================================================================
-- ROLLBACK;